### ISSUE TITLE
UID-Safe potentially vulnerable to a predictable state

### ISSUE THREAD

**Issue by jondb** [crypto-utils/uid-safe#8]
# summary

Potentially vulnerable to an attack where entropy is exhausted and the library falls back to predictable random byte generation.

Code should warn the operator when entropy is exhausted to detect attack.

# issue

The code tries crypto.randomBytes and silently falls back to crypto.pseudoRandomBytes which can happen if entropy is exhausted.

    function randomBytes(length, callback) {
      crypto.randomBytes(length, function (err, buf) {
        if (!err) return callback(null, buf)
        crypto.pseudoRandomBytes(length, function (err, buf) {
          if (err) return callback(err)
          callback(null, buf)
        })
      })
    }

Notes from [crypto documentation](https://nodejs.org/api/crypto.html#crypto_crypto_pseudorandombytes_size_callback):

> NOTE: Will throw error or invoke callback with error, if there is not enough accumulated entropy to generate cryptographically strong data. In other words, crypto.randomBytes without callback will not block even if all entropy sources are drained.

> [crypto.pseudoRandomBytes] Generates non-cryptographically strong pseudo-random data. The data returned will be unique if it is sufficiently long, but is not necessarily unpredictable. For this reason, the output of this function should never be used where unpredictability is important, such as in the generation of encryption keys.

**Comment by jonathanong** [comment]
i believe this is false in the latest version of iojs now.

**Comment by dougwilson** [comment]
Correct, in the current version of io.js, they are just aliases for the two different functions (`pseudoRandomBytes` is no longer documented on io.js because of this). But for older versions like Node.js, it does do something different in rare cases. The fallback was added to overcome a missing feature (which is also in io.js currently) where the cal doesn't just block until there is enough entropy. We can come up with a more comprehensive solution here rather than using `pseudoRandomBytes`, though, for old Node.js versions.

**Comment by dougwilson** [comment]
I spent some time today to abstract out all the random number stuff into a new module: `random-bytes`. It does not use the `pseudoRandomBytes` function, which should close out this issue.
